### PR TITLE
Clean npm package from dev files

### PR DESCRIPTION
**Pull request by ai**
@mafintosh same as https://github.com/mafintosh/multicast-dns/pull/44

### CODE REVIEW

**Comment by ai** [comment]
@mafintosh ping :(

**Comment by ai** [comment]
@mafintosh any updates?

**Comment by mafintosh** [comment]
Sorry, I don't really use .npmignore. It's too much trouble for me to maintain and benefit is tiny. Round trips are the real cost of npm anyways.

**Comment by ai** [comment]
Maybe you should add `files` section in `package.json` in this case? The problem still exists.

Problem is not in download speed, but `node_modules` size on the disk. Everyone is complaining about it. If every maintainer will be careful we can reduce size twice.

**Comment by mafintosh** [comment]
I don't personally see it as a problem that it has to download a couple of kb more. Maintaining a files array in package.json has the same issues as .npmignore maintenance wise. Thanks for the suggestion though :)

**Pull request closed without merging**
